"""add city to itinerary

Revision ID: e3edb34fa26a
Revises: c4d341e3de77
Create Date: 2019-06-10 13:29:09.254368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3edb34fa26a'
down_revision = 'c4d341e3de77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary', sa.Column('city', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary', 'city')
    # ### end Alembic commands ###
